app/app/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('core.urls')),
    path('admin/', admin.site.urls),
    path('members/', include('members.urls')),
    path('members/', include('django.contrib.auth.urls')),
]

app/members/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('login_user/', views.login_user, name='login_user'),
    path('logout_user/', views.log_out_user, name='logout_user'),
    path('register_user/', views.RegisterPage.as_view(), name='register_user'),
    path('Home/', views.Home, name='home'),
    path('people/', views.People.as_view(), name='people'),
    path('show_user/<user_id>', views.show_user, name='user_detail'),
    path('search_user/', views.SearchUser.as_view(), name='search_user'),
    path('add_user/', views.AddUser.as_view(), name='add_user'),
    path('projects/', views.ShowProjects.as_view(), name='show_projects'),
    path('project_detail/<name>', views.project_detail, name='project_detail'),
    path('create_project', views.CreateProject.as_view(), name='create_project'),
    path('update_project/<str:pk>/', views.UpdateProject.as_view(), name='update_project'),
    path('delete_project/<str:pk>/', views.DeleteProject.as_view(), name='delete_project'),
    path('update_user/<str:pk>', views.UpdateUser.as_view(), name='update_user'),
    path('delete_user/<str:pk>', views.DeleteUser.as_view(), name='delete_user'),
    path('assign_project_to_user/<str:pk>', views.AssignProjectToUser.as_view(), name='assign_project_to_user'),
    path('issues/', views.ShowIssues.as_view(), name='issues'),
    path('update_issue/<str:pk>/', views.UpdateOrCreateIssue.as_view(), name='update_or_create_issue'),
    path('delete_issue/<str:pk>/', views.DeleteIssue.as_view(), name='delete_issue'),
    path('get_project_issues/<str:pk>/', views.GetProjectIssues.as_view(), name='get_project_issues'),


]

app/core/models.py
from django.db import models
from django.contrib.auth.models import (
    AbstractUser,
    BaseUserManager,
    PermissionsMixin
)
from django.utils import timezone


class Project(models.Model):
    name = models.CharField(max_length=257, unique=True, null=False)
    description = models.TextField()
    active_issue_count = models.IntegerField(default=0, null=True)  # functiona bağlanmalı
    solved_issue_count = models.IntegerField(default=0, null=True)  # functiona bağlanmalı
    is_active = models.BooleanField()
    start_date = models.DateTimeField(default=timezone.now)
    deadline = models.DateTimeField(null=True)

    def __str__(self):
        return self.name


class UserManager(BaseUserManager):

    def create_user(self, username, email, password=None, project=None, **extra_fields):
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.username = username
        user.is_staff = True
        user.current_project = project
        user.save(using=self.db)

        return user

    def create_superuser(self, username, email, password):
        user = self.create_user(username, email, password)
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self.db)

        return user


# Create your models here.
class User(AbstractUser, PermissionsMixin):
    objects = UserManager()
    total_worked_project = models.IntegerField(default=0)  # functiona bağla
    active_work_project_count = models.IntegerField(default=0)  # functiona bağla
    project_list = models.TextField(null=True)

    REQUIRED_FIELDS = ['email']

    def __str__(self):
        return self.username


class Issue(models.Model):
    name = models.CharField(max_length=257, unique=True, null=False)
    description = models.TextField()
    is_active = models.BooleanField()
    related_project = models.ForeignKey(Project, on_delete=models.CASCADE, null=True)
    opened_by = models.CharField(max_length=257, null=False)
    assigned_by = models.CharField(max_length=257, null=True)
    assigned_to = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    assignment_date = models.DateTimeField(null=True)
    created_at = models.DateTimeField(default=timezone.now)
    deadline = models.DateTimeField(null=True)
    related_issues = models.TextField()  # kaldırılabilir

    def __str__(self):
        return self.name


class UserProjectRelation(models.Model):
    project = models.ForeignKey(Project, on_delete=models.PROTECT)
    user = models.ForeignKey(User, on_delete=models.PROTECT)

app/members/models.py
from django.db import models

# Create your models here.

app/members/forms.py
from django import forms
from django.forms import ModelForm
from core.models import User, Project, Issue


class UserForm(ModelForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password']
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Name'}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Email'}),
            'password': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Password'}),

        }


class UserUpdateForm(ModelForm):
    current_project = forms.ModelChoiceField(queryset=Project.objects.all(), empty_label=None)

    class Meta:
        model = User
        fields = ['username', 'email', 'is_staff', 'is_active', 'date_joined',
                  'total_worked_project', 'active_work_project_count', 'current_project']
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Name'}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Email'}),
            'current_project': forms.Select(attrs={'class': 'custom-control'}),
            'is_staff': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
            'is_active': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
            'date_joined': forms.DateTimeInput(attrs={'class': 'form-control'}),
            'total_worked_project': forms.NumberInput(attrs={'class': 'form-control'}),
            'active_work_project_count': forms.NumberInput(attrs={'class': 'form-control'})

        }


class ProjectForm(ModelForm):
    path = forms.CharField(required=False)

    class Meta:
        model = Project
        fields = '__all__'


class IssuesForm(ModelForm):
    class Meta:
        model = Issue
        fields = ['name', 'description', 'is_active', 'related_project', 'opened_by', 'assigned_by', 'assigned_to',
                  'assignment_date', 'created_at', 'deadline']

app/members/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.views import View
from django.views.generic import TemplateView
from django.shortcuts import render
from core.models import User, UserManager, Project, UserProjectRelation, Issue
from django.core.paginator import Paginator
from .forms import UserForm, ProjectForm, UserUpdateForm, IssuesForm
from .filters import ProjectFilter
from django.http import HttpResponseRedirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required


def get_user_current_projects(user_id):
    projects = UserProjectRelation.objects.filter(user__id=user_id).values('project')
    project_names = []
    for project in projects:
        project_names.append(Project.objects.get(id=project.get('project')).name)

    return ', '.join(project_names)


def check_user_project_relation_exist(user_id, project_id):
    relations = UserProjectRelation.objects.filter(user__id=user_id)
    for relation in relations:
        if relation.project.id == project_id:
            return True
    return False


@login_required(login_url="login_user")
def Home(request):
    return render(request, 'main/home.html', {})


def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)

        if user is not None:

            login(request, user)
            return redirect('home')
        else:
            messages.info(request, "User name OR password is not correct !")
            return redirect('login_user')
    else:
        return render(request, 'members/login.html', {})


def log_out_user(request):
    logout(request)
    return redirect('login_user')


class People(LoginRequiredMixin, View):
    login_url = 'login_user'

    def get(self, request):
        # for i in range(20):
        #     user_name = 'Test'+str(i)
        #     user_mail = user_name+'@test.com'
        #     password = "test"
        #     User.objects.create_user(user_name,user_mail,password)

        paginator = Paginator(User.objects.all(), 3)
        page = request.GET.get('page')
        users = paginator.get_page(page)
        nums = ["page"] * users.paginator.num_pages

        return render(request, 'members/people_second.html', {'users': users, 'nums': nums})


def show_user(request, user_id):
    try:
        user = User.objects.get(id=user_id)
    except:
        user = None
    return render(request, 'members/user_detail.html', {'user': user})


class SearchUser(View):

    def post(self, request):
        empty_list = False
        searched = request.POST.get('searched')
        searched_users = User.objects.filter(username__icontains=searched)
        if len(searched_users) == 0:
            empty_list = True

        return render(request, 'members/user_search.html',
                      {'searched': searched, 'users': searched_users, 'empty_list': empty_list})

    def get(self, request):
        return render(request, 'members/user_search.html', {})


class AddUser(LoginRequiredMixin, View):
    login_url = 'login_user'

    def post(self, request):
        form = UserForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data

            User.objects.create_user(data['username'], data['email'], data['password'], )
            return redirect('home')

    def get(self, request):
        projects = Project.objects.all()
        form = UserForm()
        return render(request, 'members/add_user.html', {'form': form, 'projects': projects})


class ShowProjects(LoginRequiredMixin, View):
    login_url = 'login_user'

    def get(self, request):
        project_list = Project.objects.all()
        total_projects = len(project_list)
        project_filter = ProjectFilter(request.GET, queryset=project_list)
        project_list = project_filter.qs
        # for i in range(20):
        #     name = "Test"+str(i)
        #     Projects.objects.create(name=name,description="deneme", is_active=True)
        paginator = Paginator(project_list, 3)
        page = request.GET.get('page')
        projects = paginator.get_page(page)
        nums = ["page"] * projects.paginator.num_pages

        return render(request, 'members/projects_second.html',
                      {'projects': projects, 'nums': nums, 'total_projects': total_projects,
                       'project_filter': project_filter, 'criteria': project_filter.data})


def project_detail(request, name):
    try:
        project = Project.objects.get(name=name)
    except:
        project = None
    return render(request, 'members/project_detail.html', {'project': project})


class CreateProject(LoginRequiredMixin, View):
    login_url = 'login_user'

    def post(self, request):
        form = ProjectForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('show_projects')

    def get(self, request):
        form = ProjectForm()
        return render(request, 'members/create_project_old.html', {'form': form})


class UpdateProject(LoginRequiredMixin, View):
    login_url = 'login_user'
    def post(self, request, pk):
        form = request.POST
        Project.objects.filter(id=pk).update(name=form.get('name'), description=form.get('description'),
                                             active_issue_count=form.get('active_issue_count'),
                                             solved_issue_count=form.get('solved_issue_count'),
                                             start_date=form.get('start_date'), deadline=form.get('deadline'))

        return redirect('show_projects')

    def get(self, request, pk):
        project = Project.objects.get(id=pk)
        form = ProjectForm(instance=project)

        return render(request, 'members/create_project_old.html', {'form': form})


class DeleteProject(LoginRequiredMixin, View):
    login_url = 'login_user'

    def post(self, request, pk):
        project = Project.objects.get(id=pk)
        users = User.objects.filter(current_project_id=project.id)
        if users:
            for user in users:
                User.objects.filter(id=user.id).update(current_project_id=None)

        project.delete()
        return redirect('show_projects')

    def get(self, request, pk):
        project = Project.objects.get(id=pk)
        return render(request, 'members/delete_project.html', {'project': project})


class UpdateUser(LoginRequiredMixin, View):
    login_url = 'login_user'
    def post(self, request, pk):

        user = User.objects.get(id=pk)
        form = UserUpdateForm(request.POST, instance=user)
        if form.is_valid():
            form.save()
            return redirect('people')
        else:
            # formu kaydet
            return redirect('members/update_user.html', {'form': form})

    def get(self, request, pk):
        user = User.objects.get(id=pk)
        form = UserUpdateForm(instance=user)
        return render(request, 'members/update_user.html', {'form': form})


class DeleteUser(LoginRequiredMixin, View):
    login_url = 'login_user'

    def post(self, request, pk):
        user = User.objects.get(id=pk)
        user.delete()

        return redirect('people')

    def get(self, request, pk):
        user = User.objects.get(id=pk)
        return render(request, 'members/delete_user.html', {'user': user})


class AssignProjectToUser(LoginRequiredMixin, View):
    login_url = 'login_user'

    def post(self, request, pk):
        user = User.objects.get(id=pk)
        project = Project.objects.get(id=request.POST.get('project'))
        if check_user_project_relation_exist(pk, project.id):
            messages.info(request, 'The project already assigned')
            projects = Project.objects.all()
            return render(request, 'members/assign_project_to_user.html', {'user': user, 'projects': projects})

        UserProjectRelation.objects.create(user=user, project=project)
        project_list = get_user_current_projects(pk)
        User.objects.filter(id=pk).update(project_list=project_list)
        username = None

        return redirect('people')

    def get(self, request, pk):
        user = User.objects.get(id=pk)
        projects = Project.objects.all()
        return render(request, 'members/assign_project_to_user.html', {'user': user, 'projects': projects})


class ShowIssues(LoginRequiredMixin, View):
    login_url = 'login_user'

    def get(self, request):
        # for i in range(20):
        #     name = 'Test'+str(i)
        #     desc = name + 'description'
        #     created_by = request.user.get_username()
        #
        #     Issue.objects.create(name=name,description=desc,opened_by=created_by, is_active=True)

        paginator = Paginator(Issue.objects.all(), 3)
        page = request.GET.get('page')
        issues = paginator.get_page(page)
        print(issues)
        nums = ["page"] * issues.paginator.num_pages

        return render(request, 'members/issues.html', {'issues': issues, 'nums': nums})


class UpdateOrCreateIssue(LoginRequiredMixin, View):
    login_url = 'login_user'

    def post(self, request, pk=None):
        form = request.POST
        user = None
        project = None

        if form.get('assigned_to') is not None:
            user = User.objects.get(id=form.get('assigned_to'))
        if form.get('related_project') is not None:
            project = Project.objects.get(id=form.get('assigned_to'))

        is_active = None
        if form.get('is_active') is None:
            is_active = False
        else:
            is_active = True

        if pk == 'None':
            Issue.objects.create(
                name=form.get('name'), description=form.get('description'),

app/templates/members/assign_project_to_user.html
{% extends 'main/main.html' %}
{% load static%}
{% block content %}
<div class="row" style="padding-left: 20px; padding-top: 20px">
    <div class="col-md-6">
        <div class="card text-center text-white  mb-3" id="delete-warn">
            {% if messages %}
              <ul class="messages">
                  {% for message in messages %}
                  <li>{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                  {% endfor %}
              </ul>
            {% endif %}
         <div class="card-header">
			  		<h5 class="card-title">Pick the project you want to assign to {{user}}</h5>
         </div>
         <div class="card card-body">
            <form action="{% url 'assign_project_to_user' user.id %}" method="POST">
                {% csrf_token %}
                 <select class="form-select" aria-label="Default select example" name="project">
                 <option selected>Projects</option>
                 {% for project in projects%}

                 <option value="{{project.id}}" name="project">{{project}}</option>
                 {% endfor %}

                 </select>
                <br>
                <br>
                <a class="btn btn-info" href="{% url 'people'%}">Cancel</a>
                <input class="btn btn-danger" type="submit" name="Confirm" value="Submit">


            </form>
         </div>
        </div>
    </div>
</div>

{% endblock %}

app/templates/members/create_project.html
{% extends 'main/main.html' %}
{% load static%}
 {% block content %}
<div class="row">
    <div class="col-md-6">
        <div class="card card-body">
            <form action="" method="POST">
                {% csrf_token %}

                {% for field in form %}
                <div class="fieldWrapper">
                {{ field.label_tag }} {{ field }}
                </div>
                {% endfor %}
            <input class="btn btn-success" type="submit" name="Submit" value="Submit">

            </form>
        </div>
    </div>
</div>





 {% endblock %}

app/templates/members/delete_issue.html
{% extends 'main/main.html' %}
{% load static%}
{% block content %}
<div class="row" style="padding-left: 20px; padding-top: 20px">
    <div class="col-md-6">
        <div class="card text-center text-white  mb-3" id="delete-warn">
         <div class="card-header">
			  		<h5 class="card-title">Are you sure you want to delete "{{issue}}" ?</h5>
         </div>
         <div class="card card-body">
            <form action="{% url 'delete_issue' issue.id %}" method="POST">
                {% csrf_token %}
                <a class="btn btn-info" href="{% url 'issues'%}">Cancel</a>
                <input class="btn btn-danger" type="submit" name="Confirm" value="Submit">

            </form>
         </div>
        </div>
    </div>
</div>

{% endblock %}

app/templates/members/delete_project.html
{% extends 'main/main.html' %}
{% load static%}
{% block content %}
<div class="row" style="padding-left: 20px; padding-top: 20px">
    <div class="col-md-6">
        <div class="card text-center text-white  mb-3" id="delete-warn">
         <div class="card-header">
			  		<h5 class="card-title">Are you sure you want to delete "{{project}}" ?</h5>
         </div>
         <div class="card card-body">
            <form action="{% url 'delete_project' project.id %}" method="POST">
                {% csrf_token %}
                <a class="btn btn-info" href="{% url 'show_projects'%}">Cancel</a>
                <input class="btn btn-danger" type="submit" name="Confirm" value="Submit">

            </form>
         </div>
        </div>
    </div>
</div>





{% endblock %}

app/templates/members/delete_user.html
{% extends 'main/main.html' %}
{% load static%}
{% block content %}
<div class="row" style="padding-left: 20px; padding-top: 20px">
    <div class="col-md-6">
        <div class="card text-center text-white  mb-3" id="delete-warn">
         <div class="card-header">
			  		<h5 class="card-title">Are you sure you want to delete "{{user}}" ?</h5>
         </div>
         <div class="card card-body">
            <form action="{% url 'delete_user' user.id %}" method="POST">
                {% csrf_token %}
                <a class="btn btn-info" href="{% url 'people'%}">Cancel</a>
                <input class="btn btn-danger" type="submit" name="Confirm" value="Submit">

            </form>
         </div>
        </div>
    </div>
</div>

{% endblock %}

app/templates/members/get_project_issues.html
{% extends 'main/main.html' %}
 {% block content %}
{% if has_issue %}
<div class="row">
	<div class="col">
		<div class="col-md">
			<div class="card text-center text-white  mb-4 mt-4 ml-3" id="create-new-issue">
			  	<div class="card-header">
			  		<h5 class="card-title">Create New Issue :)</h5>
			  	</div>
			  	<div class="card-body">
                    <p class="card-text">
                        Do you have new bug ? or the customer has greate(!) new idea ? to create new issue please <a href="{% url 'update_or_create_issue' None %}">click here</a>
                    </p>
			  	</div>
			</div>
		</div>
	</div>
</div>
{% for issue in issues %}
 <div class="row">
	<div class="col">
		<div class="col-md">
			<div class="card text-center text-white  mb-4 mt-4 ml-3" id="total-orders">
			  	<div class="card-header">
			  		<h5 class="card-title">{{issue.name}}</h5>
			  	</div>
			  	<div class="card-body">
                    <p class="card-text">
                        name= {{issue.name}}<br/>
                        description= {{issue.description}}<br/>
                        is_active= {{issue.is_active}}<br/>
                        opened_by= {{issue.opened_by}}<br/>
                        assigned_by= {{issue.assigned_by}}<br/>
                        assigned_to= {{issue.assigned_to}}<br/>
                        assignment_date= {{issue.assignment_date}}<br/>
                        created_at= {{issue.created_at}}<br/>
                        deadline= {{issue.deadline}}<br/>
                    </p>
			  	</div>
			</div>
		</div>
	</div>
</div>
{% endfor %}
{% else %}
<div class="row">
	<div class="col">
		<div class="col-md">
			<div class="card text-center text-white  mb-4 mt-4 ml-3" id="delete-warn">
			  	<div class="card-header">
			  		<h5 class="card-title">No Issue Found !</h5>
			  	</div>
			  	<div class="card-body">
                    <p class="card-text">
                        No issue assigned to the project yet, to assign please <a href="{% url 'update_or_create_issue' None %}">click here</a>
                    </p>
			  	</div>
			</div>
		</div>
	</div>
</div>
{% endif %}
{% endblock %}

app/templates/members/issues.html
{% extends 'main/main.html' %}
 {% block content %}
 {%  include 'members/status_people.html' %}


 <div class="row">
   <div class="col-md-12">
    <h5>Issues:</h5>
    <hr>
    <div class="card card-body">
       <a class="btn btn-sm btn-success" href="{% url 'update_or_create_issue' None%}">Create Issue</a>
        <br/>
       <table class="table table-sm">
           <tr>
              <th>name</th>
              <th>description</th>
              <th>is_active</th>
              <th>related_project</th>
              <th>opened_by</th>
              <th>assigned_by</th>
              <th>assigned_to</th>
              <th>assignment_date</th>
              <th>created_at</th>
              <th>deadline</th>
              <th>Update</th>
              <th>Delete</th>


           </tr>
           {% for issue in issues %}
           <tr>
               <td>{{issue.name}}</td>
               <td>{{issue.description}}</td>
               <td>{{issue.is_active}}</td>
               <td><a class="link-dark" href="{% url 'project_detail' issue.related_project %}">{{issue.related_project}}</a></td>
               <td>{{issue.opened_by}}</td>
               <td>{{issue.assigned_by}}</td>
               <td>{{issue.assigned_to}}</td>
               <td>{{issue.assignment_date}}</td>
               <td>{{issue.created_at}}</td>
               <td>{{issue.deadline}}</td>
               <td><a class="btn btn-sm btn-outline-info" href="{% url 'update_or_create_issue' issue.id %}">Update</a></td>
               <td><a class="btn btn-sm btn-outline-danger" href="{% url 'delete_issue' issue.id %}">Delete</a></td>


           </tr>

           {% endfor %}
       </table>
       <nav aria-label="Page navigation example">
       <ul class="pagination justify-content-center">



        {% if issues.has_previous %}
        	<li class="page-item"><a class="page-link" href="?page=1">&laquo First</a></li>

        	<li class="page-item"><a class="page-link" href="?page={{ issues.previous_page_number }}">Previous</a></li>

        {% endif %}

        <!--
        <li class="page-item disabled"><a href="#" class="page-link">Page {{ venues.number }} of {{ venues.paginator.num_pages }}</a></li>
        -->

        {% for i in nums %}
        	<li class="page-item"><a class="page-link" href="?page={{ forloop.counter }}">{{ forloop.counter }}</a></li>

        {% endfor %}


        {% if issues.has_next %}
        	<li class="page-item"><a class="page-link" href="?page={{ issues.next_page_number }}">Next</a></li>

        	<li class="page-item"><a class="page-link" href="?page={{ issues.paginator.num_pages }}">Last &raquo</a></li>

        {% endif %}

         </ul>
        </nav>
        <br/>

    </div>

   </div>
 </div>


 {% endblock %}

app/templates/members/update_or_create_issue.html
{% extends 'main/main.html' %}
{% load static%}
 {% block content %}


<div class="row">
    <div class="col-md-6" style="padding-left: 30px; padding-top: 20px">
        <div class="card-header" id="delete-warn">
			  		<h5 class="card-title text-white ">{{operation}} Issue</h5>
         </div>
        <div class="card card-body">
            <form action="" method="POST">
                {% csrf_token %}


                <div class="form-group">
                  <label for="id_name">Name:</label>

                    <input type="text" class="form-control" name="name" maxlength="257"  id="id_name" value={{form.name.value}} >
                </div>
                <div class="form-group">
                  <label for="id_description">Description:</label>
                    <textarea class="form-control" name="description" rows="5" id="id_description" value={{form.description}} ></textarea>

                </div>
                <div class="form-row">
                    <div class="col-lg-3">
                         <label for="id_related_project">Related Project:</label>

                        <select class="form-select" name="related_project" id ="id_related_project">
                          {% for project in projects %}
                             <option value="{{project.id}}">{{project}}</option>
                          {% endfor %}
                        </select>
                    </div>
                    <div class="col-lg-3">
                         <label for="id_assigned_to">Assigned To:</label>

                        <select class="form-select" name="assigned_to" id ="id_assigned_to">
                          {% for user in users %}
                             <option value="{{user.id}}">{{user}}</option>
                          {% endfor %}
                        </select>

                    </div>


                </div>


                <div class="form-group">
                  <label for="id_opened_by">Opened By:</label>

                    <input type="text" class="form-control" name="opened_by" maxlength="257"  id="id_opened_by" value={{form.opened_by.value}} readonly>

                </div>
                <div class="form-group">
                  <label for="id_assigned_by">Assigned by:</label>

                    <input type="text" class="form-control" name="assigned_by" maxlength="257"  id="id_assigned_by" value={{form.assigned_by.value}} readonly>

                </div>


                <div class="form-check">
                    <input type="checkbox" name="is_active" class="form-check-input" id="id_is_active" checked="{{form.is_active.checked}}">
                    <label class="form-check-label" for="id_is_active">Active</label>

                </div>
                <br/>
                <div class="form-row">
                    <div class="col-lg-3">
                         <label for="id_assignment_date">Assignment Date:</label>
                         <input type="datetime-local" class="date-icon" id="id_assignment_date" name="assignment_date" placeholder="{{form.assignment_date.value}}" >
                    </div>
                    <div class="col-lg-3">
                         <label for="id_deadline">Deadline:</label>
                         <input type="datetime-local" class="date-icon" id="id_deadline" name="deadline" placeholder="{{form.deadline.value}}" >

                    </div>


                </div>
                <br/>



              <input class="btn btn-success" type="submit" name="Submit" value="Submit">

            </form>

        </div>

    </div>

    {% if form.errors %}
    <div class="alert alert-danger">
        {{ form.errors }}
    </div>
{% endif %}
</div>




 {% endblock %}

app/templates/members/update_user.html
{% extends 'main/main.html' %}
{% load static%}
 {% block content %}
<div class="row">
    <div class="col-md-6">
        <div class="card card-body">
            <form action="" method="POST">
                {% csrf_token %}

                {% for field in form %}
                <div class="fieldWrapper">
                {{ field.label_tag }} {{ field }}
                </div>
                {% endfor %}
            <input class="btn btn-success" type="submit" name="Submit" value="Submit">

            </form>
        </div>
    </div>
</div>





 {% endblock %}

app/templates/members/user_add_succes.html
% extends 'main/main.html' %}
 {% block content %}
 <center>
  <h1>User Successfully Added</h1>

 </center>
 {% endblock %}

app/templates/members/user_search.html
{% extends 'main/main.html' %}
 {% block content %}
 <center>
  <h1>search user</h1>
   {% if searched %}
      {% if empty_list %}
          <h1>Nothing found for {{searched}}</h1>
      {% else %}
          <h1>You searched for {{searched}}</h1>
      {% endif %}
      <br/>
      <table class="table table-striped table-bordered table-hover" style="max-width: 18rem;">
      {% for user in users %}
        <tr>
          <td>
            <a href="{% url 'user_detail' user.id %}">{{user}}</a><br/>
          </td>
        </tr>
      {% endfor %}
      </table>

   {% else %}
      <h1> Nothing Searched</h1>
   {% endif %}

 </center>
 {% endblock %}